### ISSUE TITLE
Model mobilefacenet with margindistillation is so large?

### ISSUE THREAD

**Issue by luan1412167** [david-svitov/margindistillation#3]
Hi, thanks for your work,
I'm testing the model, I have downloaded your margindistillation model trained with mobilefacenet but the weight is so large near 180MB, why so?

**Comment by david-svitov** [comment]
HI, it includes the last FC layer of the network, which is classified into 85,000 classes. So this is 512x85000 additional parameters. That is, approximately 174MB. This layer is not needed for inference and you can cut out it.

**Comment by luan1412167** [comment]
Thanks for your reply, 
Can I remove FC layer with `https://github.com/deepinsight/insightface/blob/master/deploy/model_slim.py` in insightface repo?
Sorry because I can't test it now, so I only want to confirm I can remove it with the script. 
I higtly appreciate your help.

**Comment by david-svitov** [comment]
Yes, it looks like you can use this script

**Comment by luan1412167** [comment]
@david-svitov thanks for your help, I have cut it. The model looks better than insightface model. Your works are awesome
